import {
  DifficultyLevel,
  ElevationUnit,
  HikingTrail,
  LengthUnit,
  RecommendedExperience,
  TimeUnit,
  TrailType,
} from "./types";
import AlgetiNationalParkForestCircuit from "../../assets/TrailImages/Algeti National Park Forest Circuit.jpg";
import AragviRiverGorgeTrail from "../../assets/TrailImages/Aragvi River Gorge Trail.jpeg";
import BatumiGreenCapeBotanicalGardenPath from "../../assets/TrailImages/Batumi Green Cape Botanical Garden Path.jpg";
import BlackSeaCoastalPath from "../../assets/TrailImages/Black Sea Coastal Path.jpeg";
import BorjomiKharagauliNationalParkLoop from "../../assets/TrailImages/Borjomi-Kharagauli National Park Loop.jpg";
import ChalaadiGlacierRoute from "../../assets/TrailImages/Chalaadi Glacier Route.jpeg";
import DavidGarejaMonasteryRidgeWalk from "../../assets/TrailImages/David Gareja Monastery Ridge Walk.jpg";
import DidgoriBattlefieldHeritagePath from "../../assets/TrailImages/Didgori Battlefield Heritage Path.jpg";
import GergetiTrinityChurchTrail from "../../assets/TrailImages/Gergeti Trinity Church Trail 2.jpeg";
import JavakhetiLakesCircuit from "../../assets/TrailImages/Javakheti Lakes Circuit.jpeg";
import KazbegiGlacierTrail from "../../assets/TrailImages/Kazbegi Glacier Trail.jpeg";
import KheviKhevsuretiConnectRoute from "../../assets/TrailImages/Khevi-Khevsureti Connect Route.jpg";
import KhevsuretiMountainPassTrek from "../../assets/TrailImages/Khevi-Khevsureti Connect Route.jpg";
import LagodekhiWaterfallTrek from "../../assets/TrailImages/Lagodekhi Waterfall Trek.jpeg";
import MachakhelaNationalParkRiverTrail from "../../assets/TrailImages/Machakhela National Park River Trail.jpg";
import MartviliCanyonCircuit from "../../assets/TrailImages/Martvili Canyon Circuit.jpg";
import MestiaToUshguliTrek from "../../assets/TrailImages/Svaneti Mestia to Ushguli Trek.jpeg";
import PrometheusCaveAndCanyonTrail from "../../assets/TrailImages/Prometheus Cave and Canyon Trail.jpg";
import PshavKhevsuretiRangeTraverse from "../../assets/TrailImages/Pshav-Khevsureti Range Traverse.jpg";
import RachaAlpineMeadowsTrek from "../../assets/TrailImages/Racha Alpine Meadows Trek.jpeg";
import TedzamiRiverValleyPath from "../../assets/TrailImages/Lagodekhi Waterfall Trek.jpeg";
import TrusoValleyExpedition from "../../assets/TrailImages/Truso Valley Expedition.jpeg";
import TushetiOmaloToDartloTrek from "../../assets/TrailImages/Tusheti Omalo to Dartlo Trek.jpeg";
import VardziaCaveCityAndKhertvisiLoop from "../../assets/TrailImages/Vardzia Cave City and Khertvisi Loop.jpg";
import VashlovaniNationalParkSafariRoute from "../../assets/TrailImages/Vashlovani National Park Safari Route.jpeg";
import TbilisiBotanicGarden from "../../assets/TrailImages/Tbilisi National Park Loop.jpg";

export const trails: HikingTrail[] = [
  {
    id: 1,
    title: "Tbilisi Botanical Garden Trail",
    description:
      "This picturesque trail winds through the historic Tbilisi Botanical Garden, offering a perfect blend of natural beauty and historical significance. Founded in the 19th century, the garden houses over 4,500 plant species. The trail takes you past cascading waterfalls, across ornate bridges, and through diverse botanical collections. It's particularly magical during spring when the cherry blossoms are in full bloom or in autumn when the leaves change color. Along the way, you'll find several viewing platforms offering panoramic views of Old Tbilisi.",
    region: "Tbilisi",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 3.2,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 120,
    heightDown: 120,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 1,
      maximum: 2,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Paved paths", "Garden trails", "Stone steps"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: true,
      bestSeason: ["Spring", "Autumn"],
    },
    facilities: {
      waterAvailability: "Several drinking fountains available",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-maintained paths, mostly paved",
    campingOptions: "No camping allowed",
    crowdLevel: {
      weekday: "Low to moderate",
      weekend: "High",
      peakSeason: "Very high",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "Partially",
    hikingPoles: "Optional",
    highlights: [
      "Botanical collections",
      "Waterfalls",
      "City views",
      "Historical structures",
    ],
    hazards: ["Slippery paths after rain"],
    nearbyAttractions: ["Old Tbilisi", "Narikala Fortress", "Sulfur Baths"],
    startingPoint: {
      name: "Botanical Garden Main Entrance",
      coordinates: {
        latitude: 41.6868,
        longitude: 44.8009,
      },
      googleMapsUrl: "https://goo.gl/maps/yourbotanicalgardenlocation",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Excellent throughout",
    image: TbilisiBotanicGarden,
    tags: [
      "Urban",
      "Family-friendly",
      "Waterfall",
      "Short hike",
      "Historical",
      "Botanical",
    ],
  },
  {
    id: 2,
    title: "Kazbegi Glacier Trail",
    description:
      "One of Georgia's most iconic hikes, this trail leads to the stunning glacier near Mount Kazbek. Starting from Gergeti Trinity Church, the path ascends through alpine meadows filled with wildflowers in summer. As you gain elevation, the landscape transforms into a rugged mountainous terrain. The trail offers breathtaking views of the Caucasus range and the Terek River valley below. The final approach to the glacier requires some basic scrambling skills, but the sight of the ancient ice formation against the majestic Mount Kazbek makes every step worthwhile. Weather can change rapidly, so proper preparation is essential.",
    region: "Mtskheta-Mtianeti",
    difficulty: {
      level: DifficultyLevel.Difficult,
      technicalDifficulty: 3,
      physicalDemand: 4,
      recommendedExperience: RecommendedExperience.Experienced,
    },
    length: 9.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 950,
    heightDown: 950,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 6,
      maximum: 7,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: [
      "Alpine meadows",
      "Rocky paths",
      "Glacier moraine",
      "Scrambling sections",
    ],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["July", "August", "September"],
    },
    facilities: {
      waterAvailability: "Limited natural sources, bring 2L minimum",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition:
      "Unmarked in sections, challenging terrain, glacier crossing",
    campingOptions: "Wild camping possible near the glacier base",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate to high",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Glacier views",
      "Mount Kazbek",
      "Alpine flora",
      "Panoramic vistas",
    ],
    hazards: [
      "Weather changes",
      "Loose rock",
      "Glacier crevasses",
      "Altitude sickness",
    ],
    equipmentNeeded: [
      "Hiking boots",
      "Layers",
      "Rain gear",
      "Sun protection",
      "First aid kit",
    ],
    nearbyAttractions: [
      "Gergeti Trinity Church",
      "Stepantsminda town",
      "Georgian Military Highway",
    ],
    startingPoint: {
      name: "Gergeti Trinity Church",
      coordinates: {
        latitude: 42.6554,
        longitude: 44.6259,
      },
      googleMapsUrl: "https://goo.gl/maps/gergetichurchlocation",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Spotty, unreliable near glacier",
    image: KazbegiGlacierTrail,
    tags: [
      "Glacier",
      "Mountain",
      "Alpine",
      "Famous landmark",
    ],
  },
  {
    id: 3,
    title: "Borjomi-Kharagauli National Park Loop",
    description:
      "This extensive trail network in one of Georgia's largest national parks offers multiple day hiking options. The main loop takes you through virgin forests, alpine meadows, and subalpine zones. The biodiversity here is remarkable, with opportunities to spot deer, bears, and golden eagles. Numerous springs with mineral water (for which Borjomi is famous) can be found along the way. The trail includes several well-maintained shelters for overnight stays. The changing ecosystems as you move through different elevations make this a fascinating journey for nature enthusiasts and wildlife photographers.",
    region: "Samtskhe-Javakheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 42,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 1450,
    heightDown: 1450,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3,
      timeUnit: TimeUnit.Days,
    },
    trailType: TrailType.Loop,
    terrain: [
      "Forest paths",
      "Alpine meadows",
      "Mountain ridges",
      "River crossings",
    ],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["June", "July", "August", "September"],
    },
    facilities: {
      waterAvailability:
        "Natural springs throughout trail, filtering recommended",
      restroomAccess: "Pit toilets at shelters only",
      parkingAvailable: true,
      publicTransportAccess: "Limited",
    },
    trailCondition: "Well-marked but can be muddy after rain",
    campingOptions: "Designated camping areas and shelters available",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Virgin forests",
      "Wildlife viewing",
      "Mineral springs",
      "Panoramic vistas",
    ],
    hazards: ["Wildlife encounters", "Remote areas", "Weather changes"],
    equipmentNeeded: [
      "Camping gear",
      "Water filter",
      "Bear spray",
      "Food for multiple days",
    ],
    nearbyAttractions: [
      "Borjomi town",
      "Borjomi mineral water park",
      "Green Monastery",
    ],
    startingPoint: {
      name: "Likani Park Entrance",
      coordinates: {
        latitude: 41.8453,
        longitude: 43.3788,
      },
      googleMapsUrl: "https://goo.gl/maps/borjomiparkentrance",
    },
    endPoint: "Same as starting point (loop trail)",
    permitRequired: true,
    cellPhoneReception:
      "Very limited, emergency satellite communication recommended",
    image: BorjomiKharagauliNationalParkLoop,
    tags: [
      "Multi-day",
      "Wildlife",
      "Forest",
      "National park",
      "Camping",
      "Springs",
    ],
  },
  {
    id: 4,
    title: "Batumi Green Cape Botanical Garden Path",
    description:
      "Located along the Black Sea coast, this trail meanders through the famous Batumi Botanical Garden. With nine distinct geographic sections representing different parts of the world, the trail offers a unique global botanical journey. The path follows the coastline at times, providing spectacular views of the Black Sea. The combination of subtropical climate and diverse plant collections creates a lush experience unlike any other in Georgia. Magnolias, bamboo groves, eucalyptus trees, and Japanese gardens are just some of the highlights.",
    region: "Adjara",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 5.3,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 180,
    heightDown: 180,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Paved paths", "Garden trails", "Coastal sections"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: true,
      bestSeason: ["April", "May", "September", "October"],
    },
    facilities: {
      waterAvailability: "Drinking fountains available",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-maintained paths throughout",
    campingOptions: "No camping allowed",
    crowdLevel: {
      weekday: "Low",
      weekend: "High",
      peakSeason: "Very high",
    },
    familyFriendly: true,
    dogFriendly: false,
    wheelchairAccessible: "Partially",
    hikingPoles: "Not necessary",
    highlights: [
      "Diverse botanical collections",
      "Sea views",
      "Japanese garden",
      "Bamboo grove",
    ],
    hazards: ["Slippery paths after rain"],
    nearbyAttractions: ["Batumi city", "Black Sea beaches", "Batumi Boulevard"],
    startingPoint: {
      name: "Botanical Garden Main Entrance",
      coordinates: {
        latitude: 41.692,
        longitude: 41.708,
      },
      googleMapsUrl: "https://goo.gl/maps/batumibotanicalgarden",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Excellent throughout",
    image: BatumiGreenCapeBotanicalGardenPath,
    tags: [
      "Botanical",
      "Coastal",
      "Family-friendly",
      "Easy access",
      "Educational",
    ],
  },
  {
    id: 5,
    title: "Svaneti Mestia to Ushguli Trek",
    description:
      "This legendary multi-day trek connects two of Svaneti's most remarkable settlements. The trail passes through remote villages with medieval defensive towers, across high mountain passes, and alongside glaciers. You'll traverse alpine meadows filled with wildflowers and cross pristine streams. The backdrop of snow-capped peaks, including Mt. Shkhara (Georgia's highest peak), creates an unforgettable landscape. Traditional Svan culture is visible throughout the journey, with opportunities to visit ancient churches and sample local cuisine.",
    region: "Samegrelo-Zemo Svaneti",
    difficulty: {
      level: DifficultyLevel.Difficult,
      technicalDifficulty: 3,
      physicalDemand: 4,
      recommendedExperience: RecommendedExperience.Experienced,
    },
    length: 57,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 3100,
    heightDown: 2200,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 4,
      maximum: 5,
      timeUnit: TimeUnit.Days,
    },
    trailType: TrailType.PointToPoint,
    terrain: [
      "Mountain paths",
      "Village roads",
      "Alpine meadows",
      "River crossings",
      "Mountain passes",
    ],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["July", "August", "September"],
    },
    facilities: {
      waterAvailability: "Natural sources, villages along the way",
      restroomAccess: "In guesthouses only",
      parkingAvailable: "At Mestia only",
      publicTransportAccess: "To Mestia and from Ushguli (seasonal)",
    },
    trailCondition: "Variable, some sections unmaintained",
    campingOptions: "Wild camping possible, guesthouses in villages",
    crowdLevel: {
      weekday: "Low to moderate",
      weekend: "Moderate",
      peakSeason: "Moderate to high",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Highly recommended",
    highlights: [
      "Medieval towers",
      "Glacier views",
      "Traditional villages",
      "Mountain passes",
    ],
    hazards: ["Weather changes", "River crossings", "Remote areas", "Altitude"],
    equipmentNeeded: [
      "Camping gear if not staying in guesthouses",
      "Weather protection",
      "Sturdy boots",
    ],
    nearbyAttractions: [
      "Mestia Museum",
      "Svaneti peaks",
      "Traditional Svan houses",
    ],
    startingPoint: {
      name: "Mestia Town Center",
      coordinates: {
        latitude: 43.0423,
        longitude: 42.7299,
      },
      googleMapsUrl: "https://goo.gl/maps/mestiatowncenter",
    },
    endPoint: {
      name: "Ushguli Village",
      coordinates: {
        latitude: 42.9149,
        longitude: 43.0133,
      },
      googleMapsUrl: "https://goo.gl/maps/ushgulivillage",
    },
    cellPhoneReception: "Limited to villages only",
    image:MestiaToUshguliTrek,
    tags: [
      "Multi-day",
      "Cultural",
      "Iconic",
      "High altitude",
      "Mountain villages",
      "UNESCO",
    ],
  },
  {
    id: 6,
    title: "Vashlovani National Park Safari Route",
    description:
      "This unique trail traverses the semi-desert landscape of Vashlovani, often called 'Georgia's Little Africa.' The path winds through pistachio woodlands, steep badlands, and arid plains that contrast dramatically with Georgia's more famous alpine regions. The biodiversity here is incredible, with opportunities to spot rare species like the Caucasian leopard, wolves, and various birds of prey. The trail includes visits to natural landmarks like the Eagle Canyon and Datvis Khvreli (Bear's Hole).",
    region: "Kakheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 18,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 420,
    heightDown: 420,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 6,
      maximum: 8,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Semi-desert", "Badlands", "Dry river beds", "Woodland"],
    seasons: {
      spring: true,
      summer: false,
      autumn: true,
      winter: true,
      bestSeason: ["April", "May", "October", "November"],
    },
    facilities: {
      waterAvailability: "None, carry all water (4L minimum per person)",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Unmarked in places, 4x4 vehicle approach required",
    campingOptions: "Designated sites with ranger permission",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Low",
      peakSeason: "Low",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Optional",
    highlights: [
      "Unique desert landscapes",
      "Wildlife viewing",
      "Eagle Canyon",
      "Geological formations",
    ],
    hazards: [
      "Heat exposure",
      "Wildlife",
      "Remote location",
      "Flash floods in rainy season",
    ],
    equipmentNeeded: [
      "Sun protection",
      "Extra water",
      "Navigation equipment",
      "First aid kit",
    ],
    nearbyAttractions: ["David Gareja Monastery", "Dedoplistskaro town"],
    startingPoint: {
      name: "Vashlovani Ranger Station",
      coordinates: {
        latitude: 41.1108,
        longitude: 46.6775,
      },
      googleMapsUrl: "https://goo.gl/maps/vashlovanirangerstation",
    },
    endPoint: "Same as starting point (loop trail)",
    permitRequired: true,
    cellPhoneReception: "None, satellite communication recommended",
    image: VashlovaniNationalParkSafariRoute,
    tags: [
      "Desert",
      "Wildlife",
      "Remote",
      "Unique landscape",
      "Bird watching",
      "National park",
    ],
  },
  {
    id: 8,
    title: "Martvili Canyon Circuit",
    description:
      "This enchanting trail loops around and through the limestone Martvili Canyon, famous for its emerald waters and vertical walls. The path includes wooden walkways built along the canyon walls, offering intimate views of the rushing Abasha River below. Multiple waterfalls create a soothing soundtrack as you hike. The trail includes access points to view ancient dinosaur footprints preserved in the limestone.",
    region: "Samegrelo-Zemo Svaneti",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 3.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 90,
    heightDown: 90,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 1,
      maximum: 2,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Wooden walkways", "Natural paths", "Steps"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["May", "June", "September"],
    },
    facilities: {
      waterAvailability: "Available at visitor center",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: "Limited",
    },
    trailCondition: "Well-maintained boardwalks and paths",
    campingOptions: "No camping allowed",
    crowdLevel: {
      weekday: "Moderate",
      weekend: "High",
      peakSeason: "Very high",
    },
    familyFriendly: true,
    dogFriendly: false,
    wheelchairAccessible: "Partially",
    hikingPoles: "Not necessary",
    highlights: [
      "Emerald waters",
      "Limestone formations",
      "Waterfalls",
      "Dinosaur footprints",
    ],
    hazards: ["Slippery boardwalks when wet"],
    nearbyAttractions: ["Martvili Monastery", "Okatse Canyon", "Balda Canyon"],
    startingPoint: {
      name: "Martvili Canyon Visitor Center",
      coordinates: {
        latitude: 42.4482,
        longitude: 42.3778,
      },
      googleMapsUrl: "https://goo.gl/maps/martvilicanyonvisitorcenter",
    },
    endPoint: "Same as starting point (loop trail)",
    entranceFee: true,
    cellPhoneReception: "Good throughout",
    image:MartviliCanyonCircuit,
    tags: [
      "Canyon",
      "Water features",
      "Family-friendly",
      "Short hike",
      "Tourist attraction",
    ],
  },
  {
    id: 9,
    title: "Lagodekhi Waterfall Trek",
    description:
      "This trail in Lagodekhi Protected Areas leads to one of Georgia's most impressive waterfalls. The path follows the Shromis Khevi gorge, crossing the river several times on wooden bridges. Ancient beech and hornbeam forests provide shade along much of the route. The diversity of fungi and moss species makes this a particularly interesting hike for naturalists. The final approach requires navigating some rocky terrain before reaching the 50-meter-high waterfall that thunders into a clear pool below.",
    region: "Kakheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 12,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 650,
    heightDown: 650,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 5,
      maximum: 6,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: ["Forest paths", "River crossings", "Rocky sections"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["May", "June", "September", "October"],
    },
    facilities: {
      waterAvailability: "Stream water available (treatment necessary)",
      restroomAccess: "At visitor center only",
      parkingAvailable: true,
      publicTransportAccess: "Limited",
    },
    trailCondition: "Well-marked but can be muddy after rain",
    campingOptions: "Camping allowed near waterfall with permit",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Large waterfall",
      "Ancient forest",
      "Biodiversity",
      "River views",
    ],
    hazards: ["Slippery rocks", "River crossings after heavy rain"],
    equipmentNeeded: [
      "Water shoes for crossings",
      "Rain gear",
      "Water filter if camping",
    ],
    nearbyAttractions: ["Lagodekhi National Park", "Black Grouse Lake Trail"],
    startingPoint: {
      name: "Lagodekhi Visitor Center",
      coordinates: {
        latitude: 41.8265,
        longitude: 46.2773,
      },
      googleMapsUrl: "https://goo.gl/maps/lagodekhivisitorcenter",
    },
    endPoint: "Same as starting point (out and back trail)",
    permitRequired: true,
    cellPhoneReception: "Good near trailhead, spotty near waterfall",
    image: LagodekhiWaterfallTrek,
    tags: ["Waterfall", "Forest", "Protected area", "Day hike", "River"],
  },
  {
    id: 10,
    title: "Tusheti Omalo to Dartlo Trek",
    description:
      "This remarkable trek connects two of Tusheti's most iconic villages, Omalo and Dartlo. The trail follows ancient shepherd paths through alpine meadows, dense forests, and dramatic mountain passes. As you hike, you'll witness the unique Tushetian architecture with distinctive slate-roofed defensive towers dotting the landscape. The trail offers breathtaking views of the Greater Caucasus range and passes through several smaller settlements where time seems to stand still. The cultural significance of this route is immense, as it has served as a lifeline between isolated mountain communities for centuries.",
    region: "Tusheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 8.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 450,
    heightDown: 320,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 3,
      maximum: 5,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.PointToPoint,
    terrain: ["Mountain paths", "Grassy trails", "Rocky sections"],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Summer"],
    },
    facilities: {
      waterAvailability: "Natural springs along route",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Moderately maintained, can be muddy after rain",
    campingOptions: "Wild camping allowed, guesthouses available in villages",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate to high",
    },
    familyFriendly: false,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Traditional Tushetian towers",
      "Alpine meadows",
      "Mountain views",
      "Cultural heritage",
    ],
    hazards: ["Weather changes", "Remote location", "Steep sections"],
    nearbyAttractions: [
      "Keselo Fortress",
      "Tusheti National Park",
      "Traditional craft workshops",
    ],
    startingPoint: {
      name: "Omalo Village Center",
      coordinates: {
        latitude: 42.3766,
        longitude: 45.6362,
      },
      googleMapsUrl: "https://goo.gl/maps/tusheti-omalo-location",
    },
    endPoint: "Dartlo Village",
    cellPhoneReception: "Limited, stronger at high points",
    image:TushetiOmaloToDartloTrek,
    tags: [
      "Cultural heritage",
      "Mountain",
      "Remote",
      "Village-to-village",
      "Scenic views",
    ],
  },
  {
    id: 11,
    title: "Gergeti Trinity Church Trail",
    description:
      "This iconic Georgian trail leads to the 14th-century Gergeti Trinity Church, perched dramatically at 2,170m against the backdrop of Mount Kazbek. Starting from Stepantsminda (Kazbegi) village, the path climbs steeply through pine forests before opening to spectacular mountain vistas. The church itself is one of Georgia's most recognizable landmarks, and reaching it on foot is a spiritual journey for many. The surrounding area offers panoramic views of the Caucasus range and the Terek River valley below. Though challenging due to elevation gain, the cultural and natural rewards make this hike unforgettable.",
    region: "Kazbegi",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 4,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 4.8,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 500,
    heightDown: 500,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: ["Dirt paths", "Rocky sections", "Forest trails"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Summer", "Early Autumn"],
    },
    facilities: {
      waterAvailability: "Bring your own water",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-trodden but rough in places",
    campingOptions: "No official camping, but nearby guesthouses available",
    crowdLevel: {
      weekday: "Moderate",
      weekend: "High",
      peakSeason: "Very high",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Gergeti Trinity Church",
      "Mount Kazbek views",
      "Alpine scenery",
    ],
    hazards: ["Steep sections", "High altitude", "Sudden weather changes"],
    nearbyAttractions: [
      "Stepantsminda Museum",
      "Sno Fortress",
      "Dariali Gorge",
    ],
    startingPoint: {
      name: "Stepantsminda (Kazbegi) Village",
      coordinates: {
        latitude: 42.6559,
        longitude: 44.6418,
      },
      googleMapsUrl: "https://goo.gl/maps/stepantsminda-village-location",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Good throughout",
    image:GergetiTrinityChurchTrail,
    tags: ["Church", "Mountain views", "Iconic", "Day hike", "Cultural site"],
  },
  {
    id: 12,
    title: "Algeti National Park Forest Circuit",
    description:
      "This serene forest trail weaves through the diverse ecosystems of Algeti National Park, showcasing some of Georgia's richest biodiversity. The path traverses ancient pine and beech forests, crossing gentle streams and opening to flower-filled meadows. The park is home to numerous endemic plant species and wildlife including deer, lynx, and various bird species. The circuit offers a perfect balance of shade and sunshine, making it ideal even on warmer days. Several viewpoints along the route provide glimpses of the surrounding mountains and valleys, while interpretive signs explain the unique ecology of this protected area.",
    region: "Kvemo Kartli",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 7.2,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 210,
    heightDown: 210,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3.5,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Forest paths", "Wooden boardwalks", "Soft ground"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Late Spring", "Early Autumn"],
    },
    facilities: {
      waterAvailability: "Stream water (requires treatment)",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Well-maintained forest paths",
    campingOptions: "Designated camping areas within the park",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Optional",
    highlights: [
      "Old-growth forest",
      "Wildlife viewing",
      "Mountain streams",
      "Wildflower meadows",
    ],
    hazards: ["Slippery paths after rain", "Occasional wildlife"],
    nearbyAttractions: [
      "Manglisi Cathedral",
      "Birtvisi Fortress",
      "Tbisi Hot Springs",
    ],
    startingPoint: {
      name: "Algeti National Park Visitor Center",
      coordinates: {
        latitude: 41.6845,
        longitude: 44.3867,
      },
      googleMapsUrl: "https://goo.gl/maps/algeti-national-park-location",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Spotty, best at higher points",
    image: AlgetiNationalParkForestCircuit,
    tags: [
      "Forest",
      "Wildlife",
      "National Park",
      "Family-friendly",
      "Biodiversity",
    ],
  },
  {
    id: 13,
    title: "Truso Valley Expedition",
    description:
      "The Truso Valley trail leads into one of Georgia's hidden gems, a remote valley nestled near the Russian border. This trail follows the vibrant turquoise waters of the Terek River through a landscape dotted with mineral springs, travertine formations, and abandoned villages. The valley features remarkable geological phenomena including bubbling volcanic waters that create colorful mineral deposits. The route passes through several deserted settlements that tell the story of the region's complex history. The relative isolation means hikers often have this spectacular landscape almost entirely to themselves, creating a profound wilderness experience despite the moderate difficulty of the terrain.",
    region: "Kazbegi",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 12.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 350,
    heightDown: 350,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 4,
      maximum: 6,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: ["River valley", "Grassy paths", "Rocky sections"],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Summer"],
    },
    facilities: {
      waterAvailability: "River water (requires treatment)",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Unmaintained natural path, fades in places",
    campingOptions: "Wild camping possible, no facilities",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Low",
      peakSeason: "Low to moderate",
    },
    familyFriendly: false,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Mineral springs",
      "Abandoned villages",
      "Turquoise river",
      "Volcanic features",
    ],
    hazards: [
      "Remote area",
      "River crossings",
      "Weather changes",
      "Border proximity",
    ],
    nearbyAttractions: [
      "Kazbegi National Park",
      "Darial Gorge",
      "Gveleti Waterfall",
    ],
    startingPoint: {
      name: "Truso Valley Entrance",
      coordinates: {
        latitude: 42.5623,
        longitude: 44.6172,
      },
      googleMapsUrl: "https://goo.gl/maps/truso-valley-location",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Very limited to none",
    image: TrusoValleyExpedition,
    tags: [
      "Remote",
      "Valley",
      "Mineral springs",
      "Abandoned settlements",
      "Geological features",
    ],
  },
  {
    id: 14,
    title: "Chalaadi Glacier Route",
    description:
      "This trail offers a unique opportunity to witness one of the most accessible glaciers in Europe. Starting near Mestia, the path winds through a magical mixed forest of pine, beech, and birch trees before opening up to reveal the sprawling Chalaadi Glacier descending from Mt. Zuruldi. The trail follows the course of the glacier-fed Chalaadi River, with its milky blue waters creating a striking contrast against the green forest. The final approach brings hikers face-to-face with the glacier's terminus, where massive ice caves occasionally form. The sound of creaking ice and rushing meltwater creates an unforgettable sensory experience against the backdrop of towering mountains.",
    region: "Svaneti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 8.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 370,
    heightDown: 370,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 3,
      maximum: 4,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: ["Forest paths", "River valley", "Moraine", "Glacial approach"],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Summer"],
    },
    facilities: {
      waterAvailability: "Glacier-fed streams (requires treatment)",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Clear but rugged path, boulder fields near glacier",
    campingOptions: "Wild camping possible but not official",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate to high",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Highly recommended",
    highlights: [
      "Active glacier",
      "Alpine forest",
      "Mountain views",
      "Glacier caves (seasonal)",
    ],
    hazards: [
      "Loose moraine near glacier",
      "Falling ice",
      "Cold temperatures near ice",
      "River crossings",
    ],
    nearbyAttractions: [
      "Mestia town",
      "Svaneti Museum of History",
      "Hatsvali Ski Resort",
    ],
    startingPoint: {
      name: "Chalaadi Forest Road End",
      coordinates: {
        latitude: 43.0578,
        longitude: 42.7894,
      },
      googleMapsUrl: "https://goo.gl/maps/chalaadi-glacier-location",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Limited in forest, better in open areas",
    image:ChalaadiGlacierRoute,
    tags: ["Glacier", "Forest", "Alpine", "Ice features", "Day hike"],
  },
  {
    id: 15,
    title: "David Gareja Monastery Ridge Walk",
    description:
      "This fascinating trail combines natural beauty with rich cultural history, traversing the semi-desert landscape surrounding the ancient David Gareja monastery complex. The path climbs a ridge dividing Georgia and Azerbaijan, offering sweeping views across colorful badlands and arid plains. The monastery itself, carved into the sandstone cliffs in the 6th century, features remarkable frescoes and cave dwellings. The trail continues along the ridge passing multiple cave churches and monastic cells, with each turn revealing new perspectives on this harsh but beautiful landscape. The contrast between the golden rock formations and the occasional green oasis creates a photographer's paradise.",
    region: "Kakheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 6.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 280,
    heightDown: 280,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2.5,
      maximum: 3.5,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Desert paths", "Rocky ridges", "Sandstone formations"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: true,
      bestSeason: ["Spring", "Autumn"],
    },
    facilities: {
      waterAvailability: "None, bring all water needed",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Unmarked but visible paths, some scrambling required",
    campingOptions: "No camping permitted near monastery",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "High",
    },
    familyFriendly: true,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Optional",
    highlights: [
      "Cave monasteries",
      "Desert landscape",
      "Ridge views",
      "Ancient frescoes",
    ],
    hazards: [
      "Exposure to sun",
      "Limited shade",
      "Border proximity",
      "Loose rocks",
    ],
    nearbyAttractions: ["Udabno village", "Sagarejo town", "Sighnaghi city"],
    startingPoint: {
      name: "David Gareja Monastery Parking",
      coordinates: {
        latitude: 41.4475,
        longitude: 45.3768,
      },
      googleMapsUrl: "https://goo.gl/maps/david-gareja-location",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Good throughout",
    image:DavidGarejaMonasteryRidgeWalk,
    tags: [
      "Monastery",
      "Desert",
      "Cultural heritage",
      "Ridge walk",
      "Border trail",
    ],
  },
  {
    id: 16,
    title: "Prometheus Cave and Canyon Trail",
    description:
      "This unique trail combines natural wonders both above and below ground. Starting at the world-famous Prometheus Cave, one of the largest cave systems in Georgia, the trail emerges to follow a scenic limestone canyon carved by the Tskhaltubo River. After exploring the cave's illuminated chambers with their spectacular stalactites and stalagmites, the path continues along the canyon rim, offering views of the turquoise waters below. Several lookout points provide opportunities to observe the interesting geological formations and lush vegetation that thrives in this microclimate. The trail features several descent points to access swimming holes, particularly refreshing during summer months.",
    region: "Imereti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 5.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 180,
    heightDown: 180,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: [
      "Paved sections",
      "Forest paths",
      "Canyon edges",
      "Cave interiors",
    ],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: true,
      bestSeason: ["Late Spring", "Summer"],
    },
    facilities: {
      waterAvailability: "Available at visitor center",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-maintained, clearly marked paths",
    campingOptions: "No camping allowed in protected area",
    crowdLevel: {
      weekday: "Moderate",
      weekend: "High",
      peakSeason: "Very high",
    },
    familyFriendly: true,
    dogFriendly: false,
    wheelchairAccessible: "Partially (cave area only)",
    hikingPoles: "Optional",
    highlights: [
      "Illuminated cave system",
      "Canyon views",
      "Swimming opportunities",
      "Karst formations",
    ],
    hazards: [
      "Slippery surfaces in cave",
      "Canyon edges",
      "Flash flood risk after heavy rain",
    ],
    nearbyAttractions: [
      "Sataplia Nature Reserve",
      "Kutaisi Historical Center",
      "Gelati Monastery",
    ],
    startingPoint: {
      name: "Prometheus Cave Visitor Center",
      coordinates: {
        latitude: 42.3803,
        longitude: 42.5995,
      },
      googleMapsUrl: "https://goo.gl/maps/prometheus-cave-location",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Good outside cave, none inside",
    image:PrometheusCaveAndCanyonTrail,
    tags: ["Cave", "Canyon", "Swimming", "Karst", "Family-friendly"],
  },
  {
    id: 17,
    title: "Machakhela National Park River Trail",
    description:
      "This enchanting trail follows the crystal-clear Machakhela River through one of Georgia's newest protected areas, showcasing pristine Colchic rainforest ecosystems. The path meanders alongside the river, crossing it several times via wooden bridges and stepping stones. Ancient chestnut, beech, and box trees create a lush canopy overhead, supporting diverse bird species and rare forest flora. The trail passes traditional Adjarian wooden houses and an old water mill before reaching a spectacular waterfall tucked away in a moss-covered gorge. The humid subtropical climate has created a unique ecosystem where Mediterranean and Caucasian species coexist, making it a biodiversity hotspot recognized by UNESCO.",
    region: "Adjara",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 6.3,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 150,
    heightDown: 150,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: [
      "Riverside paths",
      "Forest floor",
      "Wooden bridges",
      "Gravel sections",
    ],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Late Spring", "Early Summer"],
    },
    facilities: {
      waterAvailability: "River water (requires treatment)",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-maintained natural paths",
    campingOptions: "Designated camping area near visitor center",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Optional",
    highlights: [
      "Pristine river",
      "Ancient forest",
      "Waterfall",
      "Traditional architecture",
    ],
    hazards: ["Slippery rocks near river", "High humidity"],
    nearbyAttractions: [
      "Machakhela Ethnographic Museum",
      "Batumi city",
      "Goderdzi Alpine Garden",
    ],
    startingPoint: {
      name: "Machakhela National Park Visitor Center",
      coordinates: {
        latitude: 41.5237,
        longitude: 41.7156,
      },
      googleMapsUrl: "https://goo.gl/maps/machakhela-park-location",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Limited in valley areas",
    image:MachakhelaNationalParkRiverTrail,
    tags: ["River", "Forest", "Waterfall", "UNESCO site", "Family-friendly"],
  },
  {
    id: 18,
    title: "Javakheti Lakes Circuit",
    description:
      "This unique high-plateau trail connects three of Georgia's most stunning alpine lakes in the volcanic Javakheti region. Starting at Lake Paravani, Georgia's largest lake, the path traverses meadows bursting with wildflowers to reach the smaller but equally beautiful Saghamo and Khanchali lakes. The volcanic landscape features interesting lava formations and panoramic views across the Armenian border. This region is renowned for its birdwatching opportunities, particularly during migration seasons when the lakes host numerous waterfowl species. The trail passes several traditional villages where you can observe the distinct culture of the local Armenian-Georgian communities. The high elevation provides relief from summer heat but creates a shorter hiking season.",
    region: "Samtskhe-Javakheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 16.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 280,
    heightDown: 280,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 5,
      maximum: 7,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Alpine meadows", "Lakeshores", "Village paths", "Open plateau"],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Summer"],
    },
    facilities: {
      waterAvailability: "Lake water (requires treatment)",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Unmarked but visible paths, some boggy sections",
    campingOptions: "Wild camping possible, get permission near villages",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Low",
      peakSeason: "Moderate",
    },
    familyFriendly: false,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Alpine lakes",
      "Volcanic landscape",
      "Birdwatching",
      "Wildflower meadows",
    ],
    hazards: [
      "High altitude",
      "Exposure to elements",
      "Limited shelter",
      "Remote area",
    ],
    nearbyAttractions: [
      "Vardzia Cave City",
      "Khertvisi Fortress",
      "Abuli Volcano",
    ],
    startingPoint: {
      name: "Lake Paravani North Shore",
      coordinates: {
        latitude: 41.4484,
        longitude: 43.837,
      },
      googleMapsUrl: "https://goo.gl/maps/javakheti-lakes-location",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Spotty, stronger at higher points",
    image: JavakhetiLakesCircuit,
    tags: ["Lakes", "Alpine", "Bird watching", "Volcanic", "High plateau"],
  },
  {
    id: 20,
    title: "Racha Alpine Meadows Trek",
    description:
      "This high-altitude trail traverses Georgia's hidden gem - the Racha region, known for its pristine nature and sparse tourism. The path winds through lush alpine meadows dotted with traditional wooden shepherd huts called 'koshki.' Starting from the small village of Glola, the trail steadily climbs through deciduous forests before opening up to panoramic vistas of the Greater Caucasus range. Wildflowers create stunning natural tapestries during late spring and summer. Multiple crystal-clear streams cross the path, providing refreshing water sources. This relatively undiscovered route offers solitude and authentic mountain experiences away from more frequented trails, with opportunities to witness traditional pastoral lifestyles that have remained unchanged for centuries.",
    region: "Racha-Lechkhumi",
    difficulty: {
      level: DifficultyLevel.Difficult,
      technicalDifficulty: 3,
      physicalDemand: 4,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 18.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 1250,
    heightDown: 650,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 6,
      maximum: 8,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.PointToPoint,
    terrain: [
      "Alpine meadows",
      "Forest paths",
      "Rocky sections",
      "Mountain streams",
    ],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Summer"],
    },
    facilities: {
      waterAvailability: "Natural springs and streams",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Unmarked path, requires navigation skills",
    campingOptions: "Wild camping allowed, shepherd huts sometimes available",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Very low",
      peakSeason: "Low",
    },
    familyFriendly: false,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Highly recommended",
    highlights: [
      "Alpine meadows",
      "Shepherd culture",
      "Mountain views",
      "Solitude",
      "Wildflowers",
    ],
    hazards: [
      "Remote location",
      "Weather changes",
      "Limited phone reception",
      "Limited rescue access",
    ],
    nearbyAttractions: [
      "Shaori Lake",
      "Nikortsminda Cathedral",
      "Oni hot springs",
    ],
    startingPoint: {
      name: "Glola Village",
      coordinates: {
        latitude: 42.6187,
        longitude: 43.5673,
      },
      googleMapsUrl: "https://goo.gl/maps/glola-village-location",
    },
    endPoint: "Ghebi Village",
    cellPhoneReception: "Very limited to none",
    image:RachaAlpineMeadowsTrek,
    tags: ["Alpine", "Remote", "Pastoral", "Backcountry", "High mountain"],
  },
  {
    id: 21,
    title: "Black Sea Coastal Path",
    description:
      "This coastal trail follows the dramatic shoreline of Georgia's Black Sea coast, alternating between secluded pebble beaches and lush subtropical vegetation. Starting near the resort town of Kobuleti, the path traces the coastline, occasionally climbing small cliffs for breathtaking views across the sea and passing through aromatic eucalyptus groves. Small secluded coves provide perfect swimming spots during summer months. The trail passes through several fishing villages where you can sample fresh seafood and observe traditional Black Sea fishing methods. The unique microclimate supports a diverse ecosystem where Mediterranean flora thrives alongside Colchic forest species. The mesmerizing sound of waves accompanies hikers throughout this sensory-rich journey.",
    region: "Adjara",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 11.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 120,
    heightDown: 120,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 3,
      maximum: 4,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Linear,
    terrain: ["Beach", "Coastal paths", "Forest sections", "Village roads"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: true,
      bestSeason: ["Summer", "Early Autumn"],
    },
    facilities: {
      waterAvailability: "Villages along route",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Mixed surfaces, mostly well-defined paths",
    campingOptions: "Beach camping possible with permission",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "High near towns",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Not necessary",
    highlights: [
      "Coastal views",
      "Swimming beaches",
      "Subtropical flora",
      "Fishing villages",
    ],
    hazards: ["Slippery rocks", "Strong currents for swimming", "Sun exposure"],
    nearbyAttractions: [
      "Kobuleti Protected Areas",
      "Batumi Botanical Garden",
      "Gonio Fortress",
    ],
    startingPoint: {
      name: "Kobuleti Beach Park",
      coordinates: {
        latitude: 41.8251,
        longitude: 41.7792,
      },
      googleMapsUrl: "https://goo.gl/maps/kobuleti-beach-location",
    },
    endPoint: "Tsikhisdziri Village",
    cellPhoneReception: "Excellent throughout",
    image: BlackSeaCoastalPath,
    tags: ["Coastal", "Swimming", "Beach", "Subtropical", "Village-to-village"],
  },
  {
    id: 22,
    title: "Khevsureti Mountain Pass Trek",
    description:
      "This challenging high-mountain trek crosses one of Georgia's most remote and mystical regions, Khevsureti, following ancient paths once used by highlander warriors. Starting from the medieval fortress village of Shatili with its distinctive stone towers, the trail climbs steeply through diverse ecological zones to cross the dramatic Datvisjvari Pass (Bear's Pass) at 2,676m. The path passes abandoned settlements where time seems frozen, with stone shrines still adorned with animal horns from pagan rituals. Weather-beaten stone crosses mark ancient burial grounds and sacred sites. The trail demands physical endurance but rewards hikers with some of Georgia's most dramatic mountain scenery and glimpses into the unique culture of Georgia's highland warriors, who maintained independence through centuries of invasions.",
    region: "Mtskheta-Mtianeti",
    difficulty: {
      level: DifficultyLevel.Difficult,
      technicalDifficulty: 4,
      physicalDemand: 5,
      recommendedExperience: RecommendedExperience.Advanced,
    },
    length: 22.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 1580,
    heightDown: 980,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 8,
      maximum: 10,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.PointToPoint,
    terrain: [
      "Mountain paths",
      "Rocky passes",
      "Alpine meadows",
      "River crossings",
    ],
    seasons: {
      spring: false,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Mid-Summer"],
    },
    facilities: {
      waterAvailability: "Mountain springs (scattered)",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Historic path, challenging in sections",
    campingOptions: "Wild camping only",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Very low",
      peakSeason: "Low",
    },
    familyFriendly: false,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Essential",
    highlights: [
      "Medieval architecture",
      "High mountain pass",
      "Ancient shrines",
      "Cultural heritage",
    ],
    hazards: [
      "Extreme remoteness",
      "Rapid weather changes",
      "High altitude",
      "Difficult evacuation",
    ],
    nearbyAttractions: [
      "Roshka Arkhoti Valley",
      "Chaukhi Massif",
      "Abudelauri Lakes",
    ],
    startingPoint: {
      name: "Shatili Village",
      coordinates: {
        latitude: 42.6556,
        longitude: 45.1569,
      },
      googleMapsUrl: "https://goo.gl/maps/shatili-village-location",
    },
    endPoint: "Mutso Village",
    cellPhoneReception: "None",
    image: KhevsuretiMountainPassTrek,
    tags: ["High mountain", "Historical", "Cultural", "Remote", DifficultyLevel.Difficult]
    },
    {
    id: 23,
    title: "Didgori Battlefield Heritage Path",
    description:
      "This historically significant trail crosses the Didgori battlefield where King David the Builder won a decisive victory against the Seljuk Turks in 1121, a pivotal moment in Georgian history. The gently rolling path offers expansive views across meadows and foothills where Georgian forces once outmaneuvered a much larger invading army. Several monuments and information boards explain the battle tactics and historical context. The trail continues through oak and beech forests to a small chapel commemorating the victory. Spring brings wildflowers and the chance to see traditional Georgian shepherding practices as flocks are moved to summer pastures. The proximity to Tbilisi makes this an accessible day trip combining moderate hiking with rich historical insights.",
    region: "Kvemo Kartli",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 2,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 7.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 210,
    heightDown: 210,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2.5,
      maximum: 3.5,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: ["Meadow paths", "Forest trails", "Gentle hills"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Spring", "Autumn"],
    },
    facilities: {
      waterAvailability: "At memorial complex only",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-maintained, occasionally muddy after rain",
    campingOptions: "No camping permitted (heritage site)",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "High on national holidays",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "Partially (memorial area only)",
    hikingPoles: "Optional",
    highlights: [
      "Historical monuments",
      "Cultural heritage",
      "Panoramic views",
      "Educational exhibits",
    ],
    hazards: ["Few shade options in summer"],
    nearbyAttractions: [
      "Manglisi Cathedral",
      "Dmanisi Archaeological Site",
      "Bolnisi Sioni Church",
    ],
    startingPoint: {
      name: "Didgori Memorial Complex",
      coordinates: {
        latitude: 41.6719,
        longitude: 44.5047,
      },
      googleMapsUrl: "https://goo.gl/maps/didgori-memorial-location",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Good throughout",
    image: DidgoriBattlefieldHeritagePath,
    tags: [
      "Historical",
      "Educational",
      "Family-friendly",
      "Cultural heritage",
      "Day trip",
    ],
  },
  {
    id: 24,
    title: "Aragvi River Gorge Trail",
    description:
      "This picturesque trail follows the dramatic Aragvi River Gorge, one of the main historical routes connecting Georgia to Russia. Starting near the medieval Ananuri fortress complex, the path descends to the river before winding along its banks. The route alternates between dense riverside forests and open sections with views of the steep gorge walls. Several abandoned villages with their distinctive stone structures tell stories of historical mountain life. The trail crosses multiple tributaries via log bridges or stepping stones, providing refreshing spots to cool off during summer hikes. Noteworthy features include a hidden waterfall and remnants of an ancient trading route with worn stone steps. The diverse microclimates support varied flora, from alpine flowers to wild fruit trees.",
    region: "Mtskheta-Mtianeti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 13.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 340,
    heightDown: 340,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 4,
      maximum: 5.5,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: [
      "River valley",
      "Forest trails",
      "Rocky sections",
      "Stream crossings",
    ],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Late Spring", "Early Autumn"],
    },
    facilities: {
      waterAvailability: "River and streams (requires treatment)",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Variable, some overgrown sections",
    campingOptions: "Wild camping possible",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate to high near fortress",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "River gorge",
      "Ananuri fortress",
      "Hidden waterfall",
      "Abandoned villages",
    ],
    hazards: ["Slippery rocks near water", "Flash flood risk after heavy rain"],
    nearbyAttractions: [
      "Zhinvali Reservoir",
      "Georgian Military Highway",
      "Gudauri Ski Resort",
    ],
    startingPoint: {
      name: "Ananuri Fortress Complex",
      coordinates: {
        latitude: 42.1603,
        longitude: 44.7052,
      },
      googleMapsUrl: "https://goo.gl/maps/ananuri-fortress-location",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Good near fortress, spotty in gorge",
    image: AragviRiverGorgeTrail,
    tags: ["River", "Gorge", "Historical", "Waterfall", "Fortress"],
  },
  {
    id: 25,
    title: "Khevi-Khevsureti Connect Route",
    description:
      "This adventurous multi-day trek connects two of Georgia's most remote mountain regions - Khevi and Khevsureti - crossing the spectacular Chaukhi Pass (3,338m). The trail begins near Juta village at the foot of the iconic Chaukhi Massif, often called the 'Georgian Dolomites' for its jagged peaks. The first day involves a challenging ascent through a moonscape of volcanic rock and alpine meadows, with panoramic views extending to Mount Kazbek on clear days. After crossing the high pass, the trail descends into the mystical region of Khevsureti, known for its medieval tower villages and unique cultural traditions. The dramatic landscape changes from alpine to forested valleys with crystal-clear streams. This demanding trek requires proper equipment and preparation but offers one of Georgia's ultimate wilderness experiences.",
    region: "Mtskheta-Mtianeti",
    difficulty: {
      level: DifficultyLevel.Difficult,
      technicalDifficulty: 4,
      physicalDemand: 5,
      recommendedExperience: RecommendedExperience.Advanced,
    },
    length: 36.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 1850,
    heightDown: 2250,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 20,
      maximum: 25,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.PointToPoint,
    terrain: [
      "Alpine crossing",
      "Scree fields",
      "Mountain paths",
      "Forest trails",
      "River crossings",
    ],
    seasons: {
      spring: false,
      summer: true,
      autumn: false,
      winter: false,
      bestSeason: ["Mid-Summer"],
    },
    facilities: {
      waterAvailability: "Mountain streams (requires treatment)",
      restroomAccess: false,
      parkingAvailable: true,
      publicTransportAccess: false,
    },
    trailCondition: "Varied, challenging sections, requires navigation",
    campingOptions: "Wild camping necessary (multi-day trek)",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Low",
      peakSeason: "Low to moderate",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Essential",
    highlights: [
      "Chaukhi Massif",
      "High alpine pass",
      "Tower villages",
      "Dramatic landscapes",
    ],
    hazards: [
      "High altitude",
      "Exposure",
      "Weather changes",
      "Remoteness",
      "Difficult terrain",
    ],
    nearbyAttractions: [
      "Roshka Lakes",
      "Abudelauri Lakes",
      "Khada Gorge",
      "Shatili",
    ],
    startingPoint: {
      name: "Juta Village",
      coordinates: {
        latitude: 42.5578,
        longitude: 44.7256,
      },
      googleMapsUrl: "https://goo.gl/maps/juta-village-location",
    },
    endPoint: "Roshka Village",
    cellPhoneReception: "Very limited to none",
    image: KheviKhevsuretiConnectRoute,
    tags: [
      "Multi-day",
      "High mountain",
      "Remote",
      "Alpine crossing",
      "Technical",
    ],
  },
  {
    id: 26,
    title: "Tedzami River Valley Path",
    description:
      "This gentle riverside trail explores the serene Tedzami River Valley, an area rich in biodiversity just an hour from Tbilisi. The path begins at the historic Rkoni Monastery, a 7th-century stone complex partially reclaimed by nature, before following the Tedzami River upstream. The trail weaves through deciduous forests, open meadows, and past several charming wooden water mills. Numerous bird species inhabit the valley, making it a paradise for birdwatchers, especially during migration seasons. Several natural pools along the river provide perfect swimming spots during summer months. The trail features remnants of Georgia's industrial heritage, including an abandoned Soviet-era mineral water factory whose buildings are now covered in colorful graffiti art. The relatively flat terrain makes this an accessible but rewarding hike for all ages.",
    region: "Shida Kartli",
    difficulty: {
      level: DifficultyLevel.Easy,
      technicalDifficulty: 1,
      physicalDemand: 1,
      recommendedExperience: RecommendedExperience.Beginner,
    },
    length: 8.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 150,
    heightDown: 150,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 2,
      maximum: 3,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.OutAndBack,
    terrain: ["Riverside path", "Forest trails", "Meadow sections"],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: true,
      bestSeason: ["Spring", "Early Summer"],
    },
    facilities: {
      waterAvailability: "River water (requires treatment)",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Well-maintained, mostly flat path",
    campingOptions: "Permitted in designated areas",
    crowdLevel: {
      weekday: "Low",
      weekend: "Moderate",
      peakSeason: "Moderate",
    },
    familyFriendly: true,
    dogFriendly: true,
    wheelchairAccessible: "Partially (first section only)",
    hikingPoles: "Not necessary",
    highlights: [
      "Historic monastery",
      "River swimming",
      "Birdwatching",
      "Water mills",
    ],
    hazards: ["Slippery banks near river"],
    nearbyAttractions: [
      "Kaspi town",
      "Uplistsikhe Cave Town",
      "Grakliani Hill archaeological site",
    ],
    startingPoint: {
      name: "Rkoni Monastery Parking",
      coordinates: {
        latitude: 41.9236,
        longitude: 44.4739,
      },
      googleMapsUrl: "https://goo.gl/maps/rkoni-monastery-location",
    },
    endPoint: "Same as starting point (out and back trail)",
    cellPhoneReception: "Good throughout",
    image:TedzamiRiverValleyPath,
    tags: ["River", "Monastery", "Family-friendly", "Swimming", "Birdwatching"],
  },
  {
    id: 27,
    title: "Pshav-Khevsureti Range Traverse",
    description:
      "This challenging high-altitude traverse crosses the remote Pshav-Khevsureti mountain range, connecting villages that were once important centers of pagan traditions later blended with Christianity. The trail begins at the Pshavi village of Shuapkho and climbs steadily through spruce forests into alpine meadows dotted with rhododendrons. After crossing the windswept Khadotani Pass (2,900m), the trail offers spectacular panoramic views before descending into Khevsureti's Arkhoti Valley. Along the way, hikers pass several 'khati' - sacred shrines where ancient pagan rituals are still performed annually. The trail requires self-sufficiency and good navigation skills, but rewards adventurers with pristine wilderness and insights into Georgia's most mystical mountain cultures. Weather can change rapidly at these elevations, demanding appropriate gear and experience.",
    region: "Mtskheta-Mtianeti",
    difficulty: {
      level: DifficultyLevel.Difficult,
      technicalDifficulty: 5,
      physicalDemand: 5,
      recommendedExperience: RecommendedExperience.Advanced,
    },
    length: 42.0,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 2300,
    heightDown: 1950,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 27,
      maximum: 32,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.PointToPoint,
    terrain: [
      "Alpine terrain",
      "Scree slopes",
      "Mountain paths",
      "Forest sections",
      "Stream crossings",
    ],
    seasons: {
      spring: false,
      summer: true,
      autumn: false,
      winter: false,
      bestSeason: ["Mid-Summer"],
    },
    facilities: {
      waterAvailability: "Mountain springs (scattered)",
      restroomAccess: false,
      parkingAvailable: false,
      publicTransportAccess: false,
    },
    trailCondition: "Barely marked, requires excellent navigation",
    campingOptions: "Wild camping required (multi-day trek)",
    crowdLevel: {
      weekday: "Very low",
      weekend: "Very low",
      peakSeason: "Low",
    },
    familyFriendly: false,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Essential",
    highlights: [
      "Sacred shrines",
      "Alpine wilderness",
      "Remote villages",
      "Cultural heritage",
    ],
    hazards: [
      "Extreme remoteness",
      "Navigation challenges",
      "Altitude sickness",
      "Severe weather",
    ],
    nearbyAttractions: [
      "Udzilaurta shrine",
      "Barisakho village",
      "Mutso fortress",
    ],
    startingPoint: {
      name: "Shuapkho Village",
      coordinates: {
        latitude: 42.3954,
        longitude: 44.9973,
      },
      googleMapsUrl: "https://goo.gl/maps/shuapkho-village-location",
    },
    endPoint: "Arkhoti Valley",
    cellPhoneReception: "None",
    image: PshavKhevsuretiRangeTraverse,
    tags: ["Expedition", "Remote", "High mountain", "Cultural", "Multi-day"],
  },
  {
    id: 28,
    title: "Vardzia Cave City and Khertvisi Loop",
    description:
      "This fascinating cultural trail combines two of Georgia's most impressive historical monuments with beautiful landscape hiking. Starting from the 12th-century Vardzia cave city, dramatically carved into a cliff face, the trail follows an ancient pilgrimage route along the Mtkvari River valley. After exploring the honeycomb-like cave monastery with its hidden church and wine cellars, the path continues through a semi-desert landscape with unique volcanic formations. The trail climbs to panoramic viewpoints offering views across to Armenia before reaching the imposing Khertvisi Fortress, one of Georgia's oldest and most strategic castles. The loop returns along the opposite side of the valley through traditional villages where you can observe rural Georgian life and farming practices. Spring brings colorful wildflowers to this otherwise arid landscape.",
    region: "Samtskhe-Javakheti",
    difficulty: {
      level: DifficultyLevel.Moderate,
      technicalDifficulty: 2,
      physicalDemand: 3,
      recommendedExperience: RecommendedExperience.Intermediate,
    },
    length: 14.5,
    lengthUnit: LengthUnit.Kilometers,
    heightUp: 450,
    heightDown: 450,
    elevationUnit: ElevationUnit.Meters,
    estimatedTime: {
      minimum: 5,
      maximum: 7,
      timeUnit: TimeUnit.Hours,
    },
    trailType: TrailType.Loop,
    terrain: [
      "Rocky paths",
      "River valley",
      "Village roads",
      "Historical sites",
    ],
    seasons: {
      spring: true,
      summer: true,
      autumn: true,
      winter: false,
      bestSeason: ["Spring", "Autumn"],
    },
    facilities: {
      waterAvailability: "Available at monuments and villages",
      restroomAccess: true,
      parkingAvailable: true,
      publicTransportAccess: true,
    },
    trailCondition: "Mixed, cultural site paths and rural roads",
    campingOptions: "Not recommended (protected historical area)",
    crowdLevel: {
      weekday: "Moderate",
      weekend: "High",
      peakSeason: "Very high at Vardzia",
    },
    familyFriendly: true,
    dogFriendly: false,
    wheelchairAccessible: "No",
    hikingPoles: "Recommended",
    highlights: [
      "Cave monastery",
      "Medieval fortress",
      "River valley",
      "Cultural heritage",
    ],
    hazards: [
      "Sun exposure",
      "Limited shade",
      "Steep sections at historical sites",
    ],
    nearbyAttractions: [
      "Vanis Kvabebi Monastery",
      "Tmogvi Fortress",
      "Aspindza town",
    ],
    startingPoint: {
      name: "Vardzia Visitor Center",
      coordinates: {
        latitude: 41.3804,
        longitude: 43.2843,
      },
      googleMapsUrl: "https://goo.gl/maps/vardzia-location",
    },
    endPoint: "Same as starting point (loop trail)",
    cellPhoneReception: "Good near monuments, variable between",
    image: VardziaCaveCityAndKhertvisiLoop,
    tags: ["Historical", "Cultural", "Cave city", "Fortress", "River valley"],
  },
];
